### ISSUE TITLE
Library link not working

### ISSUE THREAD

**Issue by chilarai** [BlockSettle/terminal#977]
I was trying to compile the application and in the **Terminal Prerequisites** section, there is a library, **[Mpir](http://[mpir.org](http://mpir.org/)/)** which doesnt exist anymore. Do you have a clone or fork of the repository?

**Comment by sergey-chernikov** [comment]
[MPIR release](https://drive.google.com/file/d/1mxoxUoDoO21JnbtBsnLeZq3x4zNvGYXE/view?usp=share_link)
[MPIR debug](https://drive.google.com/file/d/1_NTI6UFFZgvSrbupo0atMIX06xYvkwBJ/view?usp=share_link)

**Comment by sergey-chernikov** [comment]
MPIR 3.0.0 is actually available from github, but it doesn't build anyway due to OpenSSL issues.

**Comment by chilarai** [comment]
Thanks for providing the links. However, I found a clone [https://github.com/wbhart/mpir](https://github.com/wbhart/mpir), if anyone finds it valuable.
I will go with the `.lib` libraries provided by you.
